import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  architectureSidebar: [{
    type: 'category',
    label: 'Architecture',
    link: {type: 'generated-index', slug: '/', description: 'Concorde modules, features, contracts, and bounded views.'},
    items: [{type: 'autogenerated', dirName: '.'}],
  }],
};

export default sidebars;
