import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  featuresSidebar: [{
    type: 'category',
    label: 'Feature specifications',
    link: {type: 'generated-index', slug: '/', description: 'Canonical Concorde feature specifications.'},
    items: [{type: 'autogenerated', dirName: '.'}],
  }],
};
export default sidebars;
