import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  featuresSidebar: [{
    type: 'category',
    label: 'Features',
    link: {type: 'generated-index', slug: '/', description: 'Canonical Concorde features: each opens on its TL;DR, with the specification and design reference one link away.'},
    items: [{type: 'autogenerated', dirName: '.'}],
  }],
};
export default sidebars;
