"""An offline wheelhouse for installing Concorde into a temporary consumer project.

The installer provisions the managed runtime with ``pip install --no-index`` from
``PIP_FIND_LINKS``. Instead of downloading the locked requirements, this helper repacks the
distributions this test environment already has installed (``langgraph`` and everything it
requires) into wheels, so the consumer runtime receives its own real copies of every dependency and
passes the launcher's dependency isolation check without any network access.
"""

from __future__ import annotations

import base64
import hashlib
import zipfile
from importlib import metadata
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT_REQUIREMENT = "langgraph"


def _closure(name: str) -> list[metadata.Distribution]:
    seen: dict[str, metadata.Distribution] = {}
    pending = [name]
    while pending:
        key = canonicalize_name(pending.pop())
        if key in seen:
            continue
        distribution = metadata.distribution(key)
        seen[key] = distribution
        for raw in distribution.requires or ():
            requirement = Requirement(raw)
            if requirement.marker and not requirement.marker.evaluate({"extra": ""}):
                continue
            pending.append(requirement.name)
    return list(seen.values())


def _record_hash(content: bytes) -> str:
    encoded = base64.urlsafe_b64encode(hashlib.sha256(content).digest())
    return "sha256=" + encoded.rstrip(b"=").decode()


def _repack(distribution: metadata.Distribution, directory: Path) -> Path:
    name = distribution.metadata["Name"].replace("-", "_")
    version = distribution.version
    tags = [
        line.split(":", 1)[1].strip()
        for line in (distribution.read_text("WHEEL") or "").splitlines()
        if line.startswith("Tag:")
    ] or ["py3-none-any"]
    parts = [
        ".".join(dict.fromkeys(tag.split("-")[index] for tag in tags))
        for index in range(3)
    ]
    wheel = directory / f"{name}-{version}-{'-'.join(parts)}.whl"
    site = Path(str(distribution.locate_file("")))
    rows = []
    record_path = None
    with zipfile.ZipFile(wheel, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for file in distribution.files or ():
            relative = file.as_posix()
            if relative.startswith("..") or "__pycache__" in file.parts:
                continue  # Console scripts and caches are regenerated by pip.
            if relative.endswith(".dist-info/RECORD"):
                record_path = relative
                continue
            if relative.endswith(("/INSTALLER", "/REQUESTED", "/direct_url.json")):
                continue
            path = site / file
            if not path.is_file():
                continue
            content = path.read_bytes()
            archive.writestr(relative, content)
            rows.append(f"{relative},{_record_hash(content)},{len(content)}")
        assert record_path, f"{distribution.metadata['Name']} has no RECORD"
        rows.append(f"{record_path},,")
        archive.writestr(record_path, "\n".join(rows) + "\n")
    return wheel


def wheelhouse(directory: Path) -> Path:
    """Fill ``directory`` with repacked wheels for the runtime's locked requirement."""
    directory.mkdir(parents=True, exist_ok=True)
    for distribution in _closure(ROOT_REQUIREMENT):
        _repack(distribution, directory)
    return directory
